# Project: Smart Health Consulting System
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -std=c++11 -D__DEBUG__
CC       = gcc.exe -std=c++11 -D__DEBUG__
WINDRES  = windres.exe
OBJ      = main.o patient.o user.o doctor.o appointment.o hospital.o payment.o record.o
LINKOBJ  = main.o patient.o user.o doctor.o appointment.o hospital.o payment.o record.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = "Smart Health Consulting  System.exe"
CXXFLAGS = $(CXXINCS) -std=gnu++11 -g3
CFLAGS   = $(INCS) -std=gnu++11 -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.cpp
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS)

patient.o: patient.cpp
	$(CPP) -c patient.cpp -o patient.o $(CXXFLAGS)

user.o: user.cpp
	$(CPP) -c user.cpp -o user.o $(CXXFLAGS)

doctor.o: doctor.cpp
	$(CPP) -c doctor.cpp -o doctor.o $(CXXFLAGS)

appointment.o: appointment.cpp
	$(CPP) -c appointment.cpp -o appointment.o $(CXXFLAGS)

hospital.o: hospital.cpp
	$(CPP) -c hospital.cpp -o hospital.o $(CXXFLAGS)

payment.o: payment.cpp
	$(CPP) -c payment.cpp -o payment.o $(CXXFLAGS)

record.o: record.cpp
	$(CPP) -c record.cpp -o record.o $(CXXFLAGS)
