/******************************
Class Payment
Implemented by Nurulain Basirah Binti Hamid (73779)
******************************/

/*Class payment implementation file*/
#include <iostream>
#include <string>
#include <fstream>
#include <ctime>

#include "payment.h"
#include "patient.h"

using namespace std;

/*Constructor*/
Payment::Payment(){}

/*Setter*/
void Payment::setPaymentAppointmentID(string aid) {paymentAppointmentID = aid;}
void Payment::setPaymentDate(string pd) {paymentDate = pd;}
void Payment::setPaymentTime(string pt) {paymentTime = pt;}
void Payment::setPaymentIllness(string pi) {paymentIllness = pi;}
void Payment::setPaymentDoctor(string pdoc) {paymentDoctor = pdoc;}
void Payment::setPaymentSpecialization(string ps) {paymentSpecialization = ps;}
void Payment::setPaymentTotalPrice(double ptp) {paymentTotalPrice = ptp;}

/*Getter*/
string Payment::getPaymentAppointmentID() {return paymentAppointmentID;}
string Payment::getPaymentDate() {return paymentDate;}
string Payment::getPaymentTime() {return paymentTime;}
string Payment::getPaymentIllness() {return paymentIllness;}
string Payment::getPaymentDoctor() {return paymentDoctor;}
string Payment::getPaymentSpecialization() {return paymentSpecialization;}
double Payment::getPaymentTotalPrice() {return paymentTotalPrice;}


//function for patient to make payment
void Payment::makePayment()
{
	string aid, pd, pt, pi, pdoc, ps, blank;
	string cost, empty;
	
	system("cls");
	system("Color F0");
	cout << "=====================================================" << endl;
	cout << "          SMART HEALTH CONSULTING SYSTEM             " << endl;
	cout << "=====================================================" << endl;
	cout << "\n";
	cout << "----------------------Payment----------------------" << endl;
	
	ifstream patApp;
	patApp.open("Appointment.txt");
	ofstream payment("Payment.txt", ofstream::app);
	while(!patApp.eof())
	{
		getline(patApp, aid);
		paymentAppointmentID = aid;
		getline(patApp, pd);
		paymentDate = pd;
		getline(patApp, pt);
		paymentTime = pt;
		getline(patApp, pi);
		paymentIllness = pi;
		getline(patApp, pdoc);
		paymentDoctor = pdoc;
		getline(patApp, ps);
		paymentSpecialization = ps;
		
		paymentTotalPrice = 100; //every appointment will be automitaclly set at rm 100 price
		
		    cout << "     Appointment ID >> " << aid << "\n";
			cout << "     Appointment Date >> " << pd << "\n";
			cout << "     Appointment Time >> " << pt << "\n";
			cout << "     Illness >> " << pi << "\n";
			cout << "     Doctor >> " << pi << "\n";
			cout << "     Specialization >> " << pi << "\n";
			cout << "-----------------------------------------";
			payment << "RM" <<paymentTotalPrice << endl;
			
			cout << "\n  Note: Receipt will be generated by the hospital admin and will be send to you once you have done with the payment";
	}
	payment.close();
    patApp.close();
    
    system("pause");

}


//function for patient to view payment
void Payment::viewPayment()
{
	string pay, space, aid, pd, pt, pi, pdoc, ps;
	int i = 1;
	
	system("cls");
	system("Color F0");
	cout << "=====================================================" << endl;
	cout << "          SMART HEALTH CONSULTING SYSTEM             " << endl;
	cout << "=====================================================" << endl;
	cout << "\n";
	cout << "----------------------Payment----------------------" << endl;
	
	ifstream payment;
	payment.open("Payment.txt");
	
	if(!payment)
	{
		cout << "\n Sorry but there is no payment recorded in the system. ";
		system("pause");
		payment.close();
	}
	else
	{
		cout << "Payment list: " << endl;
 
		while(!payment.eof())
		{
			
		getline(payment, aid);
		getline(payment, pd);
		getline(payment, pt);
		getline(payment, pi);
		getline(payment, ps);
		getline(payment, pdoc);
			
			getline(payment, space);
			cout << "\n     Appointment ID: " << aid <<"\n";
			cout << "     Appointment Date: " << pd << "\n";
			cout << "     Appointment Time: " << pt << "\n";
			cout << "     Illness: " << pi << "\n";
			cout << "     Doctor: " << pi << "\n";
			cout << "     Specialization: " << pi << "\n";
			cout << space;
			i++;
		}
		payment.close();
		system("pause");
	}
}
